name: Node.js CI

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [10.x, 12.x]

  steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
      node-version: ${{ matrix.node-version }}

   - name: Install Packages and build
     run: |
      npm install
      npm run build --if-present

   - name: Deploy to GH Pages
     env:
      REACT_APP_EMAILJS_SERVICE: ${{secrets.REACT_APP_EMAILJS_SERVICE}}
      REACT_APP_EMAILJS_TEMPLATE: ${{secrets.REACT_APP_EMAILJS_TEMPLATE}}
      REACT_APP_EMAILJS_USER: ${{secrets.REACT_APP_EMAILJS_USER}}
     run: |
      git config --global user.name ${{secrets.USER_NAME}}
      git config --global user.email ${{secrets.USER_EMAIL}}
      git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USER_NAME}}/portfolioreact.git
      npm run deploy
